#######################################################################################
# Book settings
title: Research Software Engineering with Python
author: |
  various <a href="https://github.com/alan-turing-institute/rse-course/graphs/contributors">contributors</a>.
  Developed at <a href="https://turing.ac.uk">The Alan Turing Institute</a> based on the <a href="https://github.com/UCL/rsd-engineeringcourse">UCL RSD course</a>.
logo: docs/ATI_logo_black_W1024px.png
only_build_toc_files: true

#######################################################################################
# Execution settings
execute:
  execute_notebooks: force

#######################################################################################
# HTML-specific settings
html:
  favicon: docs/favicon.ico
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_navbar: |
    <p>Download notes as <a href="/rse-course/pdf/book.pdf">PDF</a>.</p>
    <p>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.</p>
  extra_footer: |
    <p>Creative Commons Attribution 2.0 Generic (<a href="https://creativecommons.org/licenses/by/2.0/">CC BY 2.0</a>).</p>

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false  # Use html > extra_footer instead

#######################################################################################
# Git repository settings
repository:
  url: https://github.com/alan-turing-institute/rse-course
  branch: main
